# Generated by Django 4.0 on 2022-07-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_frequentlyaskedquestions_rename_users_stores_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'ddd'},
        ),
    ]
