# Generated by Django 4.0 on 2022-07-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_commodity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodities'},
        ),
    ]
