# Generated by Django 4.0 on 2022-07-19 14:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_country_options_alter_stores_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
