# Generated by Django 4.0 on 2022-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='last_name'),
        ),
    ]
