# Generated by Django 4.0 on 2022-07-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_consumer_first_name_alter_consumer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darsher',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
