# Generated by Django 4.0 on 2022-07-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_stores_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_duration_of_transit',
            field=models.TimeField(null=True),
        ),
    ]
