# Generated by Django 4.0 on 2022-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_city_uid_commodity_uid_consumer_uid_country_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='closing_time',
            field=models.DateTimeField(null=True, verbose_name='closing_time'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='opening_time',
            field=models.DateTimeField(null=True, verbose_name='opening_time'),
        ),
    ]
