# Generated by Django 4.0 on 2022-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_darsher_darsher_order_status_consumer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darsher',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='darsher',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='phone_number'),
        ),
    ]
