# Generated by Django 4.0 on 2022-07-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_darsher_email_darsher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AlterField(
            model_name='darsher',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='core.consumer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='darsher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='darsher', to='core.darsher'),
        ),
    ]
