# Generated by Django 4.0 on 2022-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_order_order_alter_darsher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(related_name='order', to='core.Commodity'),
        ),
    ]
