# Generated by Django 4.0 on 2022-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='darsher_order_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accept'), ('REJECTED', 'Reject')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reviews',
            field=models.TextField(max_length=200, verbose_name='reviews'),
        ),
    ]
