# Generated by Django 4.0 on 2022-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_order_darsher_order_status_alter_order_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proposed_arrival_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_of_creation_of_order',
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.CharField(max_length=2000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=models.CharField(max_length=2000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='darsher_order_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accept'), ('REJECTED', 'Reject')], max_length=200, null=True, verbose_name='darsher_orders_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_spot',
            field=models.CharField(max_length=200, verbose_name='delivery_spot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_duration_of_transit',
            field=models.TimeField(null=True, verbose_name='estimated_time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_arrived',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_arrived'),
        ),
    ]
