# Generated by Django 4.0 on 2022-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_order_proposed_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_arrived',
            field=models.DateTimeField(verbose_name='time_arrived'),
        ),
    ]
