# Generated by Django 4.0 on 2022-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_order_reviews_reviews_order_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewss', to='core.Reviews'),
        ),
    ]
