# Generated by Django 4.0 on 2022-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_order_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_duration_of_transit',
            field=models.DurationField(null=True, verbose_name='estimated_time'),
        ),
    ]
