# Generated by Django 4.0 on 2022-08-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_commodity_store_stores_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_involved', to='core.stores'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.CharField(max_length=2000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=models.CharField(max_length=2000, verbose_name='question'),
        ),
    ]
