# Generated by Django 4.0 on 2022-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_store_alter_frequentlyaskedquestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_arrived',
            field=models.DateTimeField(null=True, verbose_name='time_arrived'),
        ),
    ]
