# Generated by Django 4.0 on 2022-08-02 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_city_created_at_alter_city_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('darsher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='darsher_bidding', to='core.darsher')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_for_bidding', to='core.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
