# Generated by Django 4.0 on 2022-08-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_orderbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbid',
            name='darsher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='darsher_bidding', to='core.darsher'),
        ),
        migrations.AlterField(
            model_name='orderbid',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_for_bidding', to='core.order'),
        ),
    ]
