# Generated by Django 4.0 on 2022-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_consumer_user_alter_darsher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbid',
            name='status',
            field=models.CharField(choices=[('BID SUCCESSFUL', 'Successful'), ('BID NOT SUCCESSFUL', 'Unsuccessful')], default='BID NOT SUCCESSFUL', max_length=20, verbose_name='bid_status'),
        ),
    ]
