# Generated by Django 4.0 on 2022-08-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_order_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='darsher',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='darshercompany',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='orderbid',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterField(
            model_name='stores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='core.customuser'),
        ),
    ]
