# Generated by Django 4.0 on 2022-08-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_consumer_options_alter_darsher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='core.customuser'),
        ),
    ]
